In [2]:
import numpy as np

import time

Adding or Removing Data

In [3]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([0,9,8,7])
arr3 = np.array([6,5,4,3])

combined =np.concatenate((arr1,arr2,arr3))
print(combined)

[1 2 3 4 0 9 8 7 6 5 4 3]


In [7]:
orignal = np.array([[1,2,3],
                    [4,5,6],
                    [0,0,0]])
new_array = np.array([0,8,7])
# vstack say hun row add kr sakta hain
add_new_row = np.vstack((orignal,new_array))
print(add_new_row)


col = np.array([[1],[2],[3]])
add_new_col = np.hstack((orignal,col))

print(add_new_col)


arr = np.array([1,2,3,4,5,6,7,8,9])
delete = np.delete(arr,6)
print(delete)


[[1 2 3]
 [4 5 6]
 [0 0 0]
 [0 8 7]]
[[1 2 3 1]
 [4 5 6 2]
 [0 0 0 3]]
[1 2 3 4 5 6 8 9]
