Creating arry from list

In [ ]:
import numpy as np
import time

Creating arry from list

In [3]:
arr_1d = np.array([1,2,3,4])
print("1d arry:" ,arr_1d)

arr_2d = np.array ([[1,2,3,3],[2,4,6,8]])
print("2d arry:" ,arr_2d)

1d arry: [1 2 3 4]
2d arry: [[1 2 3 3]
 [2 4 6 8]]


list vs numpy array

python list ko hum arry be bolta hain 
numy array is tarha use hota hain { pn_array = n.array} np hum ne import kia hai

In [11]:
py_list = [1,2,3,4]
print("python list multiplication" , py_list * 2)

np_array  = np.array ([2,4,5,6])  # har element 2 say ye jo number mila ga os say multipy ho ga
print("python arry multiplication" , np_array * 2)


start = time.time()
py_list = [i*2 for i in  range(1000000) ]
print("\n List operation time :" , time.time()- start) # ye hai hum basic classic list ko kesa * kr sakta hain

start = time.time()
np_array = np.arange(1000000) * 2
print("\n Numpy operation time :" , time.time()- start)



python list multiplication [1, 2, 3, 4, 1, 2, 3, 4]
python arry multiplication [ 4  8 10 12]

 List operation time : 0.28091931343078613

 Numpy operation time : 0.008007049560546875


Creating arrays from scratch

In [ ]:
zeros = np.zeros((7,8)) # is me ye hai sary zero show ho ga like 7 rows 0 ki 8 column 0 ka
print("Zeros array : \n" , zeros)

ones = np.ones((2,4))
print("Ones array : \n " , ones)

full = np.full((3,4) ,7) # 7 ye wo value hai jo ap ne 3,4 me rakhi hai means ap is ko change be kr sakta ho
print("Full array : \n " , full)

random = np.random.random((1,6))
print("Random array : \n " , random)

sequence = np.arange (0,12,4)
print("sequence array : \n " , sequence)



Zeros array : 
 [[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]
Ones array : 
  [[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Full array : 
  [[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]
Random array : 
  [[0.3206637  0.93590261 0.83027643 0.01101242 0.8065056  0.41568069]]
sequence array : 
  [0 4 8]


Vector , Matrix & Tensor

In [ ]:
vector = np.array([1,2,3]) # (1D array)
print("Vector \n" , vector)

matrix = np.array([[1,2,3],# (2D array)
                    [4,5,6]])
print("Matrix \n" , matrix)

tensor = np.array([[[1,2,3],[4,5,6],# 3D ya higher dimensional array
                    [1,2,3],[3,2,1]]])
print("Tensor \n" , tensor)


Vector 
 [1 2 3]
Matrix 
 [[1 2 3]
 [4 5 6]]
Tensor 
 [[[1 2 3]
  [4 5 6]
  [1 2 3]
  [3 2 1]]]


Array properties

In [28]:
array = np.array([[1,2,3],
                  [3,22,1]])
print("Shape :" ,array.shape)
print("Dementation :" ,array.ndim)
print("Size:" ,array.size)
print("Data_type", array.dtype)

Shape : (2, 3)
Dementation : 2
Size: 6
Data_type int64


Array Reshaping

In [47]:
array = np.arange(12)
print("Orignal Array", array )

reshaped = array.reshape((4,3))
print("Reshaped Array" , reshaped)

flattened = reshaped.flatten()
print("Flattend" , flattened) # ye copy array hota hai
 
raveled = reshaped.ravel()
print("Raveled" , raveled) # ye orignal 

#Tranpose
transpose = reshaped.T
print("Transpose" ,transpose)


Orignal Array [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped Array [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
Flattend [ 0  1  2  3  4  5  6  7  8  9 10 11]
Raveled [ 0  1  2  3  4  5  6  7  8  9 10 11]
Transpose [[ 0  3  6  9]
 [ 1  4  7 10]
 [ 2  5  8 11]]
