Numpy array operations

In [4]:
import numpy as np

In [12]:
arr = np.array([2,3,4,6,8,10,12,14])
print("Basic slicing" , arr[1:4]) # is ka matlab 1st say start kra ga or 4th element tak print kra ga
print("With step" , arr[1:9:3])# is ka matlab hum 1st of 9 number le agar 9 humara pass nhi hia to hum system 10 print kr de ga
print("Negative indexing" , arr[-4]) # is ka matlab hum last say 3rd number ley ga

Basic slicing [3 4 6]
With step [ 3  8 14]
Negative indexing 8


In [ ]:
arr_2d = np.array ([[1,2,3,4],
                    [5,6,7,8],
                    [9,10,11,12]])
print("Specfic Element", arr_2d[1,2]) # pehla row batni hai phir column
print("Entire row" , arr_2d[2]) # 2nd sari row print hovi hai
print("Entire column" , arr_2d[:,2]) # is me colun ka matlab sari row to print kro agar me mention kru pr sath
# 2nd column be print kro

Specfic Element 7
Entire row [ 9 10 11 12]
Entire column [ 3  7 11]


## Sorting


In [ ]:
unsorted = np.array([1,2,4,2,6,3,8,3,4,9,-1,-6]) # array ko sort kr ka print krta hai
print("Sorted array" , np.sort(unsorted))

arr_2d_unsorted = np.array([[1,2],
                            [2,1],
                            ])
print("2D sorted", np.sort(arr_2d_unsorted,axis=0)) # is me agar axis 0 kru to ek jesa number ( same data) ko sort kr de ga or agar
# axis 1 kru to har row ko sort kra ga

Sorted array [-6 -1  1  2  2  3  3  4  4  6  8  9]
2D sorted [[1 2]
 [1 2]]


## FIlter

In [6]:
number = np.array([1,2,3,4,9,8,7,6,5,10])
even_number = number[number % 2 == 0] # is me module 2 is lia dia hai upper jo number hain un ko 2 say divide kro agar reminder 
# o aya is ka matlab even number agar remainder 1 ho ho sakta hai number odd ho
# [number % 2 == 0] ye expression evluate hota hain jis say value niklti hai
print("Even number" , even_number)

Even number [ 2  4  8  6 10]


In [ ]:
mask = number > 7
print ("Number greater than 7" , number[mask]) # number jo array hai os me mask add krdo mask me expression as evaluatiion 
# ka lia store kia jata hai


Number greater than 7 [ 9  8 10]
[2 4 6]


In [13]:

indices = [1,3,7]
print (number[indices]) 

# ye masking ki tarha he hai
# masking me hum khud login batata hain huma krna kya hai
# where agar ye condition ture ho gi phir he hum isa result me store kra ga

where_result =np.where(number > 6)
print(where_result)
print("Where" , number[where_result])


[2 4 6]
(array([4, 5, 6, 9]),)
Where [ 9  8  7 10]


In [21]:
# jesa np.array hai array create krna ka lia same 
# np.where say be kr sakta lakin specfic condition ka sath
# (number > 5) ye humari condition hai
condition_array = np.where(number > 5 , number*3 , number)
print(condition_array)
print(where_result)

# example
# if(number > 5){
#     number*4
# } else{
#     number
# }

[ 1  2  3  4 27 24 21 18  5 30]
(array([4, 5, 6, 9]),)
